guestbook/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^specifics/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^guestbook/', include('guestbook.urls', namespace="guestbook")),
]

polls/urls.py
from django.conf.urls import url
#from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

guestbook/models.py
import datetime
from django.db import models
from django.utils import timezone



class text(models.Model):
    title_text = models.CharField(max_length=200, blank=True)
    question_text = models.TextField(blank=True)
    pub_date = models.DateTimeField('date published')
    def __str__(self):      # __unicode__ on Python 2
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):              # __unicode__ on Python 2
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):              # __unicode__ on Python 2
        return self.choice_text

guestbook/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.template import RequestContext, loader
from django.utils import timezone
from .models import text



def index(request):
    latest_question_list = text.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    try:
        title=request.POST['nafn']
        texti1=request.POST['færsla']
    except(KeyError):
        pass
    else:
        f = text(question_text=texti1, pub_date=timezone.now(),title_text=title)
        f.save()
    return render(request, 'guestbook/index.html', context)



def detail(request, question_id):
    question = get_object_or_404(text, pk=question_id)
    return render(request, 'guestbook/detail.html', {'question': question})



"""
def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)
"""

polls/views.py
#from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect#, HttpResponse
#from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

guestbook/templates/guestbook/detail.html
<title>{{question.title_text}}</title>

<h1>{{question.title_text}}</h1>

<p>{{ question.question_text }}</p>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

guestbook/templates/guestbook/index.html
<form action="/guestbook/" method="post" id="form">
  {% csrf_token %}
  <fieldset>
    <legend>Skrifaðu færslu</legend>
    Færsla<br>
    <textarea name="færsla"></textarea><br><br>
    Nafn<br>
    <input type="text" name="nafn">
    <br>
    <br>
    <input type="submit" value="Submit">
  </fieldset>
</form>
<br>
<br>


{% if latest_question_list %}
    <ul>
    {% for text in latest_question_list %}
        <li><a href="{% url 'guestbook:detail' text.id %}">{{ text.title_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No text are available.</p>
{% endif %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
<title>BleeGudjon</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>